;;; ocaml-eglot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ocaml-eglot.el

(autoload 'ocaml-eglot-setup "ocaml-eglot" "\
Setup OCaml-eglot.")
(autoload 'ocaml-eglot-clean "ocaml-eglot" "\
Clean registered hooks and advice.")
(autoload 'ocaml-eglot "ocaml-eglot" "\
Minor mode for interacting with `ocaml-lsp-server' using `eglot' as a client.

OCaml Eglot provides standard implementations of the various custom-requests
 exposed by `ocaml-lsp-server'.

This is a minor mode.  If called interactively, toggle the `OCaml-eglot
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `ocaml-eglot'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'ocaml-eglot-objinfo-handler "ocaml-eglot" "\
Display the result of `ocamlobjinfo` instead of file contents.")
(add-hook 'find-file-hook #'ocaml-eglot-objinfo-handler)
(register-definition-prefixes "ocaml-eglot" '("ocaml-eglot-"))


;;; Generated autoloads from ocaml-eglot-req.el

(register-definition-prefixes "ocaml-eglot-req" '("ocaml-eglot-req--"))


;;; Generated autoloads from ocaml-eglot-type-enclosing.el

(register-definition-prefixes "ocaml-eglot-type-enclosing" '("ocaml-eglot-type-"))


;;; Generated autoloads from ocaml-eglot-util.el

(register-definition-prefixes "ocaml-eglot-util" '("ocaml-eglot-util-"))


;;; Generated autoloads from ocaml-eglot-xref.el

(register-definition-prefixes "ocaml-eglot-xref" '("ocaml-eglot-"))

;;; End of scraped data

(provide 'ocaml-eglot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ocaml-eglot-autoloads.el ends here
