;;; git-ps1-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-ps1-mode.el

(defvar git-ps1-mode nil "\
Non-nil if Git-Ps1 mode is enabled.
See the `git-ps1-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `git-ps1-mode'.")
(custom-autoload 'git-ps1-mode "git-ps1-mode" nil)
(autoload 'git-ps1-mode "git-ps1-mode" "\
Minor-mode to print __git_ps1.

This is a global minor mode.  If called interactively, toggle the
`Git-Ps1 mode' mode.  If the prefix argument is positive, enable the
mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='git-ps1-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(autoload 'git-ps1-mode-get-current "git-ps1-mode" "\
Return current __git_ps1 execution output as string.

Give FORMAT if you want to specify other than \"%s\".
If optional argument DIR is given, run __git_ps1 in that directory.
This function returns nil if the output is not available for some reasons.

(fn &optional FORMAT DIR)")
(register-definition-prefixes "git-ps1-mode" '("git-ps1-mode-"))

;;; End of scraped data

(provide 'git-ps1-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-ps1-mode-autoloads.el ends here
