;;; ocp-indent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ocp-indent.el

(autoload 'ocp-setup-indent "ocp-indent" nil t)
(autoload 'ocp-indent-caml-mode-setup "ocp-indent")
(register-definition-prefixes "ocp-indent" '("ocp-in"))

;;; End of scraped data

(provide 'ocp-indent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ocp-indent-autoloads.el ends here
