;;; com-css-sort-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from com-css-sort.el

(autoload 'com-css-sort-attributes-block "com-css-sort" "\
Sort CSS attributes in the block.
NO-BACK-TO-LINE : Do not go back to the original line.

(fn &optional NO-BACK-TO-LINE)" t)
(autoload 'com-css-sort-attributes-document "com-css-sort" "\
Sort CSS attributes the whole documents." t)
(register-definition-prefixes "com-css-sort" '("com-css-sort-"))

;;; End of scraped data

(provide 'com-css-sort-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; com-css-sort-autoloads.el ends here
